### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by beni2a** [RahulGonal/IpCreeper#1]
Hi dear, 
I have an issue with your script.
First I had to change some indentation because i had some error of and after i have a "not callable module"
I tried some correction but didn't find where the error is.
I precise that I add my API from shodan and IPinfo correctly.
Best regards.
![Snag_204e3edc](https://user-images.githubusercontent.com/36544124/125414833-faf3628a-9688-4541-8460-367bf57709b1.png)

**Comment by RahulGonal** [comment]
thank you so much for showing interest on my module
and i am still developing will notify you when its back again

**Comment by RahulGonal** [comment]
it is fixed now and you can only use both the websites for info rather than using a single one
